### PR TITLE
Add debug npm command.

### PR DESCRIPTION
**Pull request by josephdburdick**
Running `npm run debug` initializes server-side debugging via node-inspector with settings-development.json accessible to the Meteor instance.

### CODE REVIEW

**Comment by themeteorchef** [comment]
This one is good to go. See a couple nitpicks on the other commit. Once these are set I'll merge and bump to 3.2.0. Thanks for putting these together :)

**Comment by josephdburdick** [comment]
I agree that it's really handy. I think in order for meteor folks to know what to do it should be documented somewhere. Since the README of base isn't use for that and Base's website is, I'll leave it up to you.

**Comment by themeteorchef** [comment]
Going to rope this into some other changes later. Will merge this then :)

**Comment by themeteorchef** [comment]
Going to close this out for now as I'm not seeing much demand for it (or in Slack when we chatted about it).

**Comment by josephdburdick** [comment]
Fair enough.

**Pull request closed without merging**
