### PR TITLE
added eslint linter and refactor code

### PR DESCRIPTION
**Pull request by arvi**
Just in case you plan on adding ESLint on TMC Base.

---

Upon reading the ff: articles

http://info.meteor.com/blog/set-up-sublime-text-for-meteor-es6-es2015-and-jsx-syntax-and-linting
http://www.nixtu.info/2015/03/why-to-pick-eslint-over-jslint-jshint.html

I decided to lint TMC Base and refactor codes except for client/helpers/flow-router.js (no param reassign eslint error). Haven't thought of a cleaner way to refactor it.

Why it's important: http://spin.atomicobject.com/2011/04/10/javascript-don-t-reassign-your-function-arguments/

P.S the ESLint's starting point I used was Meteor's. I just modified some of the rules to prevent major code refactoring on TMC Base.

https://github.com/arvi/eslintrc/commit/3d1c38670d9e3da22f3a41648423a951aacc7eb8

### CODE REVIEW

**Comment by themeteorchef** [comment]
Hey @arvi! Thanks for putting this together :) 

Give me a few days to review everything/wrap my head around changes. A quick skim didn't reveal anything crazy so will likely consider this. If I have any questions I will add them inline.

**Comment by jptissot** [comment]
Wow ! Thanks a lot for this.

**Comment by arvi** [comment]
@themeteorchef

Sure! I didn't do anything crazy hehe :) All eslint errors have been corrected except flowrouter on this pull request. :p

**Comment by vhf** [comment]
Nice, I'll use your branch until this gets merged. :+1:

**Comment by themeteorchef** [comment]
Going to close this out. v4.0.0 of Base will support ESLint but not specific to this ruleset. See notes here #95 on using your own `.eslintrc`.

**Pull request closed without merging**
